spring:
  datasource:
    url: jdbc:mysql://localhost:3306/session1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver